Repository Nexters/Naenio-iOS, pull requests merged in 2022-07, with the labels that each got.

#10 [Feature/network] 네트워킹 기본 템플릿 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue-bug-template.md
  .github/ISSUE_TEMPLATE/issue-feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Naenio.xcodeproj/project.pbxproj
  Naenio.xcodeproj/xcuserdata/cho-yoonyoung.xcuserdatad/xcschemes/xcschememanagement.plist
  Naenio.xcworkspace/contents.xcworkspacedata
  Naenio.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Naenio.xcworkspace/xcuserdata/cho-yoonyoung.xcuserdatad/UserInterfaceState.xcuserstate
  Naenio.xcworkspace/xcuserdata/cho-yoonyoung.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Naenio/Utils/Extension/Encodable+Extension.swift
  Naenio/Utils/Extension/String+Extension.swift
  Naenio/Utils/Extension/TargetType+Extension.swift
  Naenio/Utils/Models/LoginRequestInformation.swift
  Naenio/Utils/Network/API/NaenioAPI+Error.swift
  Naenio/Utils/Network/API/NaenioAPI+Path.swift
  Naenio/Utils/Network/API/NaenioAPI+Request.swift
  Naenio/Utils/Network/API/NaenioAPI+Task.swift
  Naenio/Utils/Network/API/NaenioAPI+Wrapper.swift
  Naenio/Utils/Network/API/NaenioAPI.swift
  Naenio/Utils/Network/Common/DefaultSession.swift
  Naenio/Utils/Network/Common/ModelType.swift
  Naenio/Utils/Network/Constants/HeaderInformation.swift
  Naenio/Utils/Network/Constants/HttpResponseCode.swift
  Podfile
  Podfile.lock
Labels: enhancement, setting

#11 [feature/dynamic-link] Support dynamic link
  Naenio.xcodeproj/project.pbxproj
  Naenio/Naenio.entitlements
  Naenio/Supporting files/NaenioApp.swift
Labels: enhancement

#15 Kakao API connection
  Naenio.xcodeproj/project.pbxproj
  Naenio/Sources/LogIn/Apple/AppleLoginManager.swift
  Naenio/Sources/LogIn/Kakao/KakaoLoginManager.swift
  Naenio/Sources/LogIn/Kakao/SignInWithKakaoButton.swift
  Naenio/Sources/LogIn/Kakao/SignInWithKakaoButtonViewModel.swift
  Naenio/Sources/LogIn/LoginTestViewModel.swift
  Naenio/Sources/LogIn/Models/LoginRequestInformation.swift
  Naenio/Sources/LogIn/Models/UserInformation.swift
Labels: bug, enhancement
